# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yura\PycharmProjects\pythonProject\my_project\furniture_factory\GUI_designer\add_personal_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogAddPersonal(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 470)
        Dialog.setStyleSheet("background-color: rgb(74, 80, 106);")
        self.BB_Ok_Cancel = QtWidgets.QDialogButtonBox(Dialog)
        self.BB_Ok_Cancel.setGeometry(QtCore.QRect(180, 430, 341, 32))
        self.BB_Ok_Cancel.setStyleSheet("background-color: rgb(145, 158, 208);")
        self.BB_Ok_Cancel.setOrientation(QtCore.Qt.Horizontal)
        self.BB_Ok_Cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.BB_Ok_Cancel.setObjectName("buttonBox")
        self.LE_FamilyName = QtWidgets.QLineEdit(Dialog)
        self.LE_FamilyName.setGeometry(QtCore.QRect(20, 50, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.LE_FamilyName.setFont(font)
        self.LE_FamilyName.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(16,240,207);\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;\n"
"")
        self.LE_FamilyName.setObjectName("lineEdit")
        reg_ex = QtCore.QRegExp("[А-Я][а-я]{30}")
        input_validator = QtGui.QRegExpValidator(reg_ex, self.LE_FamilyName)
        self.LE_FamilyName.setValidator(input_validator)
        # self.lineEdit.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp(r"[A-Z]{1,3}\\d{1,5}")))
        self.LE_Name = QtWidgets.QLineEdit(Dialog)
        self.LE_Name.setGeometry(QtCore.QRect(20, 80, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.LE_Name.setFont(font)
        self.LE_Name.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(16,240,207);\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;\n"
"")
        self.LE_Name.setObjectName("lineEdit_2")
        self.LE_Name.setValidator(input_validator)
        self.LE_FatherName = QtWidgets.QLineEdit(Dialog)
        self.LE_FatherName.setGeometry(QtCore.QRect(20, 110, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.LE_FatherName.setFont(font)
        self.LE_FatherName.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(16,240,207);\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;\n"
"")
        self.LE_FatherName.setObjectName("lineEdit_3")
        self.LE_FatherName.setValidator(input_validator)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 340, 271, 16))
        self.line.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 280, 271, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border:none;\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 310, 271, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border:none;\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 260, 271, 16))
        self.line_2.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 179, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(185, 179, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        ####################################################################
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_year = QtWidgets.QLabel(Dialog)
        self.LE_year.setGeometry(QtCore.QRect(220, 170, 71, 31))
        self.LE_year.setFont(font)
        self.LE_year.setStyleSheet("border:none;\n"
                                      "border-bottom: 1px solid rgb(16,240,207);\n"
                                      "padding_bottom: 7px;\n"
                                      "background-color: rgb(255, 255,255);\n"
                                      "border-radius: 5px;")
        self.LE_year.setText("")
        self.LE_year.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_year.setObjectName("Label_year")
        ###################################################################
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_month = QtWidgets.QLabel(Dialog)
        self.LE_month.setGeometry(QtCore.QRect(105, 169, 81, 31))
        self.LE_month.setFont(font)
        self.LE_month.setStyleSheet("border:none;\n"
                                       "border-bottom: 1px solid rgb(16,240,207);\n"
                                       "padding_bottom: 7px;\n"
                                       "background-color: rgb(255, 255,255);\n"
                                       "border-radius: 5px;")
        self.LE_month.setText("")
        self.LE_month.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_month.setObjectName("Label_month")

        ############################################################################
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 143, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.LE_NuberPhone = QtWidgets.QLineEdit(Dialog)
        self.LE_NuberPhone.setGeometry(QtCore.QRect(20, 230, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.LE_NuberPhone.setFont(font)
        self.LE_NuberPhone.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(16,240,207);\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;\n"
"")
        self.LE_NuberPhone.setPlaceholderText("+7")
        self.LE_NuberPhone.setObjectName("NuberPhone")
        self.LE_NuberPhone.setInputMask("+9 (999) 999 99-99")
        self.Label_SpaceImage = QtWidgets.QLabel(Dialog)
        self.Label_SpaceImage.setGeometry(QtCore.QRect(380, 50, 128, 128))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.Label_SpaceImage.setFont(font)
        self.Label_SpaceImage.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(161, 161, 161);")
        self.Label_SpaceImage.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_SpaceImage.setObjectName("label_5")
        self.TB_calendar = QtWidgets.QToolButton(Dialog)
        self.TB_calendar.setGeometry(QtCore.QRect(100, 142, 121, 21))
        self.TB_calendar.setStyleSheet("border:None")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "./GUI/icon/calendar [#1197].png"),

                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_calendar.setIcon(icon1)
        self.TB_calendar.setObjectName("TB_calendar")
        ################################################################
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_Day = QtWidgets.QLabel(Dialog)
        self.LE_Day.setGeometry(QtCore.QRect(20, 169, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LE_Day.setFont(font)
        self.LE_Day.setStyleSheet("border:none;\n"
                                     "border-bottom: 1px solid rgb(16,240,207);\n"
                                     "padding_bottom: 7px;\n"
                                     "background-color: rgb(255, 255,255);\n"
                                     "border-radius: 5px;")
        self.LE_Day.setText("")
        self.LE_Day.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_Day.setObjectName("Label_day")
        ######################################################################
        self.LE_BaseRate = QtWidgets.QLineEdit(Dialog)
        self.LE_BaseRate.setGeometry(QtCore.QRect(20, 370, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.LE_BaseRate.setFont(font)
        self.LE_BaseRate.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(16,240,207);\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;\n"
"")
        self.LE_BaseRate.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_BaseRate.setPlaceholderText("")
        reg_rate = QtCore.QRegExp("\d\d\d\d\d\d\d\d")
        input_validator = QtGui.QRegExpValidator(reg_rate, self.LE_BaseRate)
        self.LE_BaseRate.setValidator(input_validator)
        self.LE_BaseRate.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.LE_Attestation = QtWidgets.QLineEdit(Dialog)
        self.LE_Attestation.setGeometry(QtCore.QRect(240, 370, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.LE_Attestation.setFont(font)
        self.LE_Attestation.setStyleSheet("border:none;\n"
"border-bottom: 1px solid rgb(16,240,207);\n"
"padding_bottom: 7px;\n"
"background-color: rgb(255, 255,255);\n"
"border-radius: 5px;\n"
"")
        self.TB_calendar.raise_()
        self.label_3.raise_()
        self.LE_Attestation.setAlignment(QtCore.Qt.AlignCenter)
        self.LE_Attestation.setPlaceholderText("")
        self.LE_Attestation.setObjectName("lineEdit_7")
        reg_rate = QtCore.QRegExp("\d\d\d")
        input_validator = QtGui.QRegExpValidator(reg_rate, self.LE_Attestation)
        self.LE_Attestation.setValidator(input_validator)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(210, 350, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        ################################################################
        self.TB_AddPhoto = QtWidgets.QToolButton(Dialog)
        self.TB_AddPhoto.setGeometry(QtCore.QRect(414, 185, 61, 27))
        self.TB_AddPhoto.setStyleSheet("border : 1px solid rgb(209, 209, 209);\n"
                                      "border-radius: 5px\n"
                                      "")
        self.TB_AddPhoto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
                "./GUI/icon/camera-5-64.ico"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_AddPhoto.setIcon(icon)
        self.TB_AddPhoto.setIconSize(QtCore.QSize(23, 23))
        self.TB_AddPhoto.setShortcut("")
        self.TB_AddPhoto.setCheckable(False)
        self.TB_AddPhoto.setAutoRepeat(False)
        self.TB_AddPhoto.setObjectName("toolButton")
        #################################################################
        self.retranslateUi(Dialog)
        self.BB_Ok_Cancel.accepted.connect(Dialog.accept)
        self.BB_Ok_Cancel.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LE_FamilyName.setPlaceholderText(_translate("Dialog", "Фамилия сотрудника"))
        self.LE_Name.setPlaceholderText(_translate("Dialog", "Имя сотрудника"))
        self.LE_FatherName.setPlaceholderText(_translate("Dialog", "Очество сотрудника"))
        # self.comboBox.setCurrentText(_translate("Dialog", "Отдел проектирования"))
        # self.comboBox.setItemText(0, _translate("Dialog", "Отдел проектирования"))
        # self.comboBox.setItemText(1, _translate("Dialog", "Отдел сборки"))
        # self.comboBox.setItemText(2, _translate("Dialog", "Одел покраски"))
        # self.comboBox_2.setItemText(0, _translate("Dialog", "Инженер"))
        # self.comboBox_2.setItemText(1, _translate("Dialog", "Дизайнер"))
        # self.comboBox_2.setItemText(2, _translate("Dialog", "Мастер по дереву"))
        self.label.setText(_translate("Dialog", "-"))
        self.label_2.setText(_translate("Dialog", "-"))
        self.label_3.setText(_translate("Dialog", "Дата рождения"))
        self.label_4.setText(_translate("Dialog", "Номер телефона"))
        self.Label_SpaceImage.setText(_translate("Dialog", "ФОТО"))
        self.label_6.setText(_translate("Dialog", "Базовая ставка"))
        self.label_7.setText(_translate("Dialog", "Аттестация"))
        self.TB_AddPhoto.setText(_translate("Dialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = DialogAddPersonal()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
