# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yura\PycharmProjects\pythonProject\my_project\furniture_factory\GUI_designer\Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DialogCalendar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 272)
        Dialog.setStyleSheet("background-color: rgb(145, 158, 208);\n"
"background-color: rgb(168, 181, 208);")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 401, 231))
        self.calendarWidget.setObjectName("calendarWidget")
        self.PB_OK = QtWidgets.QPushButton(Dialog)
        self.PB_OK.setGeometry(QtCore.QRect(170, 240, 75, 23))
        self.PB_OK.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.PB_OK.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PB_OK.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = DialogCalendar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
