from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtCore import pyqtSignal





class GUIAssessment(QtWidgets.QWidget):

        def __init__(self):
            super(GUIAssessment, self).__init__()
            self.setObjectName("Form")
            self.resize(1358, 665)
            self.setStyleSheet("background-color: rgb(74, 80, 106);")
            self.WorkSpace_Assesment_Personal = QtWidgets.QFrame(self)
            self.WorkSpace_Assesment_Personal.setGeometry(QtCore.QRect(20, 50, 1321, 581))
            font = QtGui.QFont()
            font.setPointSize(10)
            self.WorkSpace_Assesment_Personal.setFont(font)
            self.WorkSpace_Assesment_Personal.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.WorkSpace_Assesment_Personal.setFrameShadow(QtWidgets.QFrame.Raised)
            self.WorkSpace_Assesment_Personal.setObjectName("WorkSpace_Assesment_Personal")
            self.gridLayout_2 = QtWidgets.QGridLayout(self.WorkSpace_Assesment_Personal)
            self.gridLayout_2.setObjectName("gridLayout_2")
            spacerItem = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem, 13, 5, 1, 1)
            spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem1, 13, 10, 1, 1)
            self.Group_DepCrit = QtWidgets.QFrame(self.WorkSpace_Assesment_Personal)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.Group_DepCrit.sizePolicy().hasHeightForWidth())
            self.Group_DepCrit.setSizePolicy(sizePolicy)
            self.Group_DepCrit.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.Group_DepCrit.setFrameShadow(QtWidgets.QFrame.Raised)
            self.Group_DepCrit.setObjectName("Group_DepCrit")
            self.gridLayout = QtWidgets.QGridLayout(self.Group_DepCrit)
            self.gridLayout.setObjectName("gridLayout")
            self.label_Crit_APers = QtWidgets.QLabel(self.Group_DepCrit)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(12)
            font.setBold(True)
            font.setWeight(75)
            self.label_Crit_APers.setFont(font)
            self.label_Crit_APers.setStyleSheet("\n"
                                                "color: rgb(255, 255, 255);")
            self.label_Crit_APers.setAlignment(QtCore.Qt.AlignCenter)
            self.label_Crit_APers.setObjectName("label_Crit_APers")
            self.gridLayout.addWidget(self.label_Crit_APers, 0, 2, 1, 1)
            self.ComboBox_Dep_APers = QtWidgets.QComboBox(self.Group_DepCrit)
            self.ComboBox_Dep_APers.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.ComboBox_Dep_APers.setObjectName("ComboBox_Dep_APers")
            self.gridLayout.addWidget(self.ComboBox_Dep_APers, 1, 0, 1, 1)
            self.Label_Dep_APers = QtWidgets.QLabel(self.Group_DepCrit)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(12)
            font.setBold(True)
            font.setWeight(75)
            self.Label_Dep_APers.setFont(font)
            self.Label_Dep_APers.setStyleSheet("\n"
                                               "color: rgb(255, 255, 255);")
            self.Label_Dep_APers.setAlignment(QtCore.Qt.AlignCenter)
            self.Label_Dep_APers.setObjectName("Label_Dep_APers")
            self.gridLayout.addWidget(self.Label_Dep_APers, 0, 0, 1, 1)
            self.ComboBox_Crit_APers = QtWidgets.QComboBox(self.Group_DepCrit)
            self.ComboBox_Crit_APers.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.ComboBox_Crit_APers.setObjectName("ComboBox_Crit_APers")
            self.gridLayout.addWidget(self.ComboBox_Crit_APers, 1, 2, 1, 1)
            spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
            self.gridLayout_2.addWidget(self.Group_DepCrit, 8, 1, 1, 2)
            spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem3, 13, 12, 1, 1)
            spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem4, 13, 7, 1, 1)
            self.PB_Load_ListPers = QtWidgets.QPushButton(self.WorkSpace_Assesment_Personal)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(10)
            font.setBold(False)
            font.setWeight(50)
            self.PB_Load_ListPers.setFont(font)
            self.PB_Load_ListPers.setStyleSheet("background-color: rgb(145, 158, 208);")
            self.PB_Load_ListPers.setObjectName("PB_Load_ListPers")
            self.gridLayout_2.addWidget(self.PB_Load_ListPers, 9, 1, 1, 2)
            self.Label_SelectDate = QtWidgets.QLabel(self.WorkSpace_Assesment_Personal)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(12)
            font.setBold(True)
            font.setWeight(75)
            self.Label_SelectDate.setFont(font)
            self.Label_SelectDate.setStyleSheet("color: rgb(255, 255, 255);")
            self.Label_SelectDate.setAlignment(QtCore.Qt.AlignCenter)
            self.Label_SelectDate.setObjectName("Label_SelectDate")
            self.gridLayout_2.addWidget(self.Label_SelectDate, 4, 1, 1, 2)
            spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
            self.gridLayout_2.addItem(spacerItem5, 10, 1, 1, 1)
            spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
            self.gridLayout_2.addItem(spacerItem6, 3, 1, 1, 1)
            spacerItem7 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem7, 5, 0, 1, 1)
            self.CalendarWidget_APers = QtWidgets.QCalendarWidget(self.WorkSpace_Assesment_Personal)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.CalendarWidget_APers.sizePolicy().hasHeightForWidth())
            self.CalendarWidget_APers.setSizePolicy(sizePolicy)
            self.CalendarWidget_APers.setStyleSheet("background-color: rgb(145, 158, 208);")
            self.CalendarWidget_APers.setObjectName("CalendarWidget_APers")
            self.gridLayout_2.addWidget(self.CalendarWidget_APers, 5, 1, 1, 2)
            self.PB_Save_APers = QtWidgets.QPushButton(self.WorkSpace_Assesment_Personal)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(10)
            font.setBold(False)
            font.setItalic(False)
            font.setUnderline(False)
            font.setWeight(50)
            font.setStrikeOut(False)
            self.PB_Save_APers.setFont(font)
            self.PB_Save_APers.setStyleSheet("\n"
                                             "background-color: rgb(209, 209, 209);")
            self.PB_Save_APers.setObjectName("PB_Save_APers")
            self.gridLayout_2.addWidget(self.PB_Save_APers, 13, 13, 1, 1)
            self.CheckBox_SingleAssesm = QtWidgets.QCheckBox(self.WorkSpace_Assesment_Personal)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(9)
            font.setBold(True)
            font.setWeight(75)
            self.CheckBox_SingleAssesm.setFont(font)
            self.CheckBox_SingleAssesm.setStyleSheet("\n"
                                                     "color: rgb(222, 222, 222);")
            self.CheckBox_SingleAssesm.setObjectName("CheckBox_SingleAssesm")
            self.gridLayout_2.addWidget(self.CheckBox_SingleAssesm, 13, 4, 1, 1)
            spacerItem8 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem8, 5, 3, 1, 1)
            spacerItem9 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
            self.gridLayout_2.addItem(spacerItem9, 13, 14, 1, 1)
            self.ComboBox_Sorting_APers = QtWidgets.QComboBox(self.WorkSpace_Assesment_Personal)
            self.ComboBox_Sorting_APers.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.ComboBox_Sorting_APers.setObjectName("ComboBox_Sorting_APers")
            self.ComboBox_Sorting_APers.addItem("")
            self.ComboBox_Sorting_APers.addItem("")
            self.ComboBox_Sorting_APers.addItem("")
            self.ComboBox_Sorting_APers.addItem("")
            self.gridLayout_2.addWidget(self.ComboBox_Sorting_APers, 1, 4, 1, 1)
            self.Label_Name_Sorting_APers = QtWidgets.QLabel(self.WorkSpace_Assesment_Personal)
            font = QtGui.QFont()
            font.setFamily("Roboto")
            font.setPointSize(9)
            self.Label_Name_Sorting_APers.setFont(font)
            self.Label_Name_Sorting_APers.setStyleSheet("color: rgb(255, 255, 255);")
            self.Label_Name_Sorting_APers.setAlignment(QtCore.Qt.AlignCenter)
            self.Label_Name_Sorting_APers.setObjectName("Label_Name_Sorting_APers")
            self.gridLayout_2.addWidget(self.Label_Name_Sorting_APers, 0, 4, 1, 1)
            self.CalendarWidget_APers.raise_()
            self.CheckBox_SingleAssesm.raise_()
            self.Group_DepCrit.raise_()
            # self.scrollArea_AListPersonal_.raise_()
            self.PB_Load_ListPers.raise_()
            self.Label_SelectDate.raise_()
            self.ComboBox_Sorting_APers.raise_()
            self.Label_Name_Sorting_APers.raise_()
            self.PB_Save_APers.raise_()
            QtCore.QMetaObject.connectSlotsByName(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = GUIAssessment()
    ui.show()
    sys.exit(app.exec_())

