from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import QDialog, QFileDialog, qApp, QWidget

class GUIPersonalWidget (QtWidgets.QWidget):
    def __init__(self, id_widget, path_icon_edit, parent=None):

        super(GUIPersonalWidget, self).__init__(parent)
        self.id = id_widget
        ##################################
        self.comment_icon = "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/comment 4.png"
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.comment_icon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.GLay_LPers = QtWidgets.QFrame(self)
        self.GLay_LPers.setGeometry(QtCore.QRect(310, 240, 512, 93))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLay_LPers.sizePolicy().hasHeightForWidth())
        self.GLay_LPers.setSizePolicy(sizePolicy)
        self.GLay_LPers.setMinimumSize(QtCore.QSize(0, 90))
        self.GLay_LPers.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.GLay_LPers.setObjectName("GLay_LPers_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.GLay_LPers)
        self.gridLayout_8.setContentsMargins(12, -1, 12, 5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.SP_Lastval = QtWidgets.QSplitter(self.GLay_LPers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SP_Lastval.sizePolicy().hasHeightForWidth())
        self.SP_Lastval.setSizePolicy(sizePolicy)
        self.SP_Lastval.setOrientation(QtCore.Qt.Vertical)
        self.SP_Lastval.setObjectName("SP_Lastval_2")
        self.label_name_Lastval = QtWidgets.QLabel(self.SP_Lastval)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_name_Lastval.setFont(font)
        self.label_name_Lastval.setObjectName("label_name_Lastval_2")
        self.label_Lastval = QtWidgets.QLabel(self.SP_Lastval)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Lastval.setFont(font)
        self.label_Lastval.setObjectName("label_Lastval_2")
        self.gridLayout_8.addWidget(self.SP_Lastval, 0, 6, 2, 1)
        self.SP_Meanval = QtWidgets.QSplitter(self.GLay_LPers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SP_Meanval.sizePolicy().hasHeightForWidth())
        self.SP_Meanval.setSizePolicy(sizePolicy)
        self.SP_Meanval.setOrientation(QtCore.Qt.Vertical)
        self.SP_Meanval.setObjectName("SP_Meanval_2")
        self.label_name_Meanval = QtWidgets.QLabel(self.SP_Meanval)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_name_Meanval.setFont(font)
        self.label_name_Meanval.setObjectName("label_name_Meanval_2")
        self.label_Meanval = QtWidgets.QLabel(self.SP_Meanval)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_Meanval.setFont(font)
        self.label_Meanval.setObjectName("label_Meanval_2")
        self.gridLayout_8.addWidget(self.SP_Meanval, 0, 5, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(7, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 1, 1, 1)
        self.label_LPersCommentAssessment_14 = QtWidgets.QToolButton(self.GLay_LPers)
        self.label_LPersCommentAssessment_14.setMinimumSize(QtCore.QSize(30, 30))
        self.label_LPersCommentAssessment_14.setStyleSheet("\n"
                                                           "border:none\\n")
        self.label_LPersCommentAssessment_14.setIcon(icon4)
        self.label_LPersCommentAssessment_14.setIconSize(QtCore.QSize(35, 35))
        self.label_LPersCommentAssessment_14.setCheckable(False)
        self.label_LPersCommentAssessment_14.setObjectName("label_LPersCommentAssessment_14")
        self.gridLayout_8.addWidget(self.label_LPersCommentAssessment_14, 2, 5, 3, 1)
        self.label_LPersPhoto = QtWidgets.QLabel(self.GLay_LPers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LPersPhoto.sizePolicy().hasHeightForWidth())
        self.label_LPersPhoto.setSizePolicy(sizePolicy)
        self.label_LPersPhoto.setMinimumSize(QtCore.QSize(64, 64))
        self.label_LPersPhoto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_LPersPhoto.setText("")
        self.label_LPersPhoto.setObjectName("label_LPersPhoto_2")
        self.gridLayout_8.addWidget(self.label_LPersPhoto, 0, 0, 4, 1)
        self.label_LPersCheckAssessment = QtWidgets.QLabel(self.GLay_LPers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LPersCheckAssessment.sizePolicy().hasHeightForWidth())
        self.label_LPersCheckAssessment.setSizePolicy(sizePolicy)
        self.label_LPersCheckAssessment.setMinimumSize(QtCore.QSize(20, 20))
        self.label_LPersCheckAssessment.setStyleSheet("border-image: url(:/newPrefix/icon/tick-mark.png);")
        self.label_LPersCheckAssessment.setText("")
        self.label_LPersCheckAssessment.setObjectName("label_LPersCheckAssessment_2")
        self.gridLayout_8.addWidget(self.label_LPersCheckAssessment, 0, 4, 1, 1)
        self.VLay_Name_LPers = QtWidgets.QFrame(self.GLay_LPers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VLay_Name_LPers.sizePolicy().hasHeightForWidth())
        self.VLay_Name_LPers.setSizePolicy(sizePolicy)
        self.VLay_Name_LPers.setObjectName("VLay_Name_LPers_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.VLay_Name_LPers)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Label_LPersLastName = QtWidgets.QLabel(self.VLay_Name_LPers)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Label_LPersLastName.setFont(font)
        self.Label_LPersLastName.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_LPersLastName.setObjectName("Label_LPersLastName_2")
        self.verticalLayout_9.addWidget(self.Label_LPersLastName)
        self.Label_LPersName = QtWidgets.QLabel(self.VLay_Name_LPers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_LPersName.sizePolicy().hasHeightForWidth())
        self.Label_LPersName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Label_LPersName.setFont(font)
        self.Label_LPersName.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_LPersName.setObjectName("Label_LPersName_2")
        self.verticalLayout_9.addWidget(self.Label_LPersName)
        self.gridLayout_8.addWidget(self.VLay_Name_LPers, 0, 2, 5, 1)
        self.verticalLayout_3.addWidget(self.GLay_LPers)