from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import QDialog, QFileDialog, qApp, QWidget
from abc import ABC, abstractmethod


class GUIPersonInteraction(QtWidgets.QWidget):

    def __init__(self):
        super(GUIPersonInteraction, self).__init__()
        self.frame_person_interaction = QtWidgets.QFrame(self)
        self.frame_person_interaction.setGeometry(QtCore.QRect(20, 10, 1291, 811))
        self.frame_person_interaction.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_person_interaction)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_loadCard = QtWidgets.QFrame(self.frame_person_interaction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_loadCard.sizePolicy().hasHeightForWidth())
        self.frame_loadCard.setSizePolicy(sizePolicy)
        self.frame_loadCard.setObjectName("frame_loadCard")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_loadCard)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 150)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.VLay_Dates = QtWidgets.QVBoxLayout()
        self.VLay_Dates.setContentsMargins(-1, 9, -1, -1)
        self.VLay_Dates.setObjectName("VLay_Dates")
        self.label_head_age = QtWidgets.QLabel(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_head_age.sizePolicy().hasHeightForWidth())
        self.label_head_age.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_head_age.setFont(font)
        self.label_head_age.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_head_age.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_head_age.setObjectName("label_head_age")
        self.VLay_Dates.addWidget(self.label_head_age)
        self.line_date = QtWidgets.QFrame(self.frame_loadCard)
        self.line_date.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_date.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_date.setObjectName("line_date")
        self.VLay_Dates.addWidget(self.line_date)
        self.label_birthDate = QtWidgets.QLabel(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_birthDate.sizePolicy().hasHeightForWidth())
        self.label_birthDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_birthDate.setFont(font)
        self.label_birthDate.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_birthDate.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_birthDate.setObjectName("label_birthDate")
        self.VLay_Dates.addWidget(self.label_birthDate)
        self.label_old = QtWidgets.QLabel(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_old.sizePolicy().hasHeightForWidth())
        self.label_old.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_old.setFont(font)
        self.label_old.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_old.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_old.setObjectName("label_age")
        self.VLay_Dates.addWidget(self.label_old)
        self.line_date_3 = QtWidgets.QFrame(self.frame_loadCard)
        self.line_date_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_date_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_date_3.setObjectName("line_date_3")
        self.VLay_Dates.addWidget(self.line_date_3)
        self.label_head_workExp = QtWidgets.QLabel(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_head_workExp.sizePolicy().hasHeightForWidth())
        self.label_head_workExp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_head_workExp.setFont(font)
        self.label_head_workExp.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_head_workExp.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_head_workExp.setObjectName("label_head_workExp")
        self.VLay_Dates.addWidget(self.label_head_workExp)
        self.line_workExp = QtWidgets.QFrame(self.frame_loadCard)
        self.line_workExp.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_workExp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_workExp.setObjectName("line_workExp")
        self.VLay_Dates.addWidget(self.line_workExp)
        self.label_workExp = QtWidgets.QLabel(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_workExp.sizePolicy().hasHeightForWidth())
        self.label_workExp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_workExp.setFont(font)
        self.label_workExp.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_workExp.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_workExp.setObjectName("label_workExp")
        self.VLay_Dates.addWidget(self.label_workExp)
        self.gridLayout_2.addLayout(self.VLay_Dates, 3, 2, 1, 1)
        self.Glay_serch_personal = QtWidgets.QGridLayout()
        self.Glay_serch_personal.setContentsMargins(-1, 80, -1, -1)
        self.Glay_serch_personal.setObjectName("Glay_serch_personal")
        self.PB_serch_personal = QtWidgets.QPushButton(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_serch_personal.sizePolicy().hasHeightForWidth())
        self.PB_serch_personal.setSizePolicy(sizePolicy)
        self.PB_serch_personal.setMaximumSize(QtCore.QSize(70, 16777215))
        self.PB_serch_personal.setStyleSheet("background-color: rgb(145, 158, 208);")
        self.PB_serch_personal.setObjectName("PB_serch_personal")
        self.Glay_serch_personal.addWidget(self.PB_serch_personal, 0, 2, 1, 1)
        self.LE_serch_personal = QtWidgets.QLineEdit(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_serch_personal.sizePolicy().hasHeightForWidth())
        self.LE_serch_personal.setSizePolicy(sizePolicy)
        self.LE_serch_personal.setMaximumSize(QtCore.QSize(16777215, 26))
        self.LE_serch_personal.setStyleSheet("\n"
                                             "background-color: rgb(255, 255, 255);\n"
                                             " border-radius: 5px;")
        self.LE_serch_personal.setText("")
        self.LE_serch_personal.setObjectName("LE_serch_personal")
        self.Glay_serch_personal.addWidget(self.LE_serch_personal, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.Glay_serch_personal, 0, 0, 1, 3)
        self.HLay_avatar = QtWidgets.QFrame(self.frame_loadCard)
        self.HLay_avatar.setMinimumSize(QtCore.QSize(0, 128))
        self.HLay_avatar.setObjectName("HLay_avatar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.HLay_avatar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_avatar = QtWidgets.QLabel(self.HLay_avatar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_avatar.sizePolicy().hasHeightForWidth())
        self.label_avatar.setSizePolicy(sizePolicy)
        self.label_avatar.setMinimumSize(QtCore.QSize(128, 128))
        self.label_avatar.setMaximumSize(QtCore.QSize(128, 128))
        self.label_avatar.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_avatar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        self.label_avatar.setFont(font)
        self.label_avatar.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avatar.setObjectName("label_avatar")
        self.horizontalLayout.addWidget(self.label_avatar)
        self.gridLayout_2.addWidget(self.HLay_avatar, 1, 1, 1, 1)
        self.GLay_bonus = QtWidgets.QFrame(self.frame_loadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLay_bonus.sizePolicy().hasHeightForWidth())
        self.GLay_bonus.setSizePolicy(sizePolicy)
        self.GLay_bonus.setObjectName("GLay_bonus")
        self.gridLayout = QtWidgets.QGridLayout(self.GLay_bonus)
        self.gridLayout.setObjectName("gridLayout")
        self.label_certification = QtWidgets.QLabel(self.GLay_bonus)
        self.label_certification.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_certification.setFont(font)
        self.label_certification.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_certification.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_certification.setObjectName("label_certification")
        self.gridLayout.addWidget(self.label_certification, 0, 0, 1, 1)
        self.label_asses_bonus = QtWidgets.QLabel(self.GLay_bonus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_asses_bonus.sizePolicy().hasHeightForWidth())
        self.label_asses_bonus.setSizePolicy(sizePolicy)
        self.label_asses_bonus.setMinimumSize(QtCore.QSize(41, 41))
        self.label_asses_bonus.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_asses_bonus.setFont(font)
        self.label_asses_bonus.setStyleSheet(" border-radius: 25px;\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(122, 133, 175);\n"
                                             "")
        self.label_asses_bonus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asses_bonus.setObjectName("label_asses_bonus")
        self.gridLayout.addWidget(self.label_asses_bonus, 1, 2, 1, 1)
        self.label_bonus = QtWidgets.QLabel(self.GLay_bonus)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_bonus.setFont(font)
        self.label_bonus.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_bonus.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_bonus.setObjectName("label_bonus")
        self.gridLayout.addWidget(self.label_bonus, 0, 2, 1, 1)
        self.label_asses_certification = QtWidgets.QLabel(self.GLay_bonus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_asses_certification.sizePolicy().hasHeightForWidth())
        self.label_asses_certification.setSizePolicy(sizePolicy)
        self.label_asses_certification.setMinimumSize(QtCore.QSize(41, 41))
        self.label_asses_certification.setMaximumSize(QtCore.QSize(71, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_asses_certification.setFont(font)
        self.label_asses_certification.setStyleSheet(" border-radius: 25px;\n"
                                                     "color: rgb(255, 255, 255);\n"
                                                     "background-color: rgb(122, 133, 175);\n"
                                                     "")
        self.label_asses_certification.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asses_certification.setObjectName("label_asses_certification")
        self.gridLayout.addWidget(self.label_asses_certification, 1, 0, 1, 1)
        # self.PB_SharePermissions = QtWidgets.QPushButton(self.GLay_bonus)
        # self.PB_SharePermissions.setMaximumSize(QtCore.QSize(150, 25))
        # self.PB_SharePermissions.setBaseSize(QtCore.QSize(0, 0))
        # font = QtGui.QFont()
        # font.setFamily("Roboto")
        # font.setPointSize(9)
        # font.setBold(False)
        # font.setItalic(False)
        # font.setUnderline(False)
        # font.setWeight(50)
        # self.PB_SharePermissions.setFont(font)
        # self.PB_SharePermissions.setStyleSheet("color: rgb(0, 0, 0);\n"
        #                                        "background-color: rgb(145, 158, 208);")
        # self.PB_SharePermissions.setObjectName("pushButton")
        # self.gridLayout.addWidget(self.PB_SharePermissions, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GLay_bonus, 3, 1, 1, 1)
        self.VLay_contact = QtWidgets.QFrame(self.frame_loadCard)
        self.VLay_contact.setObjectName("VLay_contact")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.VLay_contact)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_surname = QtWidgets.QLabel(self.VLay_contact)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_surname.setFont(font)
        self.label_surname.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_surname.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_surname.setObjectName("label_surname")
        self.verticalLayout.addWidget(self.label_surname)
        self.label_name = QtWidgets.QLabel(self.VLay_contact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_number = QtWidgets.QLabel(self.VLay_contact)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_number.sizePolicy().hasHeightForWidth())
        self.label_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_number.setFont(font)
        self.label_number.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_number.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_number.setObjectName("label_number")
        self.verticalLayout.addWidget(self.label_number)
        self.line_number_asses = QtWidgets.QFrame(self.VLay_contact)
        self.line_number_asses.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_number_asses.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_number_asses.setObjectName("line_number_asses")
        self.verticalLayout.addWidget(self.line_number_asses)
        ###################################################################
        self.HLay_right_button = QtWidgets.QHBoxLayout()
        self.HLay_right_button.setObjectName("HLay_right_button")
        self.PB_right_user = QtWidgets.QPushButton(self.VLay_contact)
        self.PB_right_user.setMaximumSize(QtCore.QSize(150, 25))
        self.PB_right_user.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.PB_right_user.setFont(font)
        self.PB_right_user.setStyleSheet("QPushButton{\n"
                                         "background-color: rgb(151, 156, 180);\n"
                                         "    color: rgb(0, 0, 0);\n"
                                         "border-style: solid;\n"
                                         "border-width: 0.5px;\n"
                                         "    border-color: rgb(151, 156, 180);\n"
                                         "border-radius: 5px;\n"
                                         "\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "background-color: rgb(140, 148, 180);\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed {\n"
                                         "border-style: inset;\n"
                                         "\n"
                                         "    \n"
                                         "    background-color: rgb(24, 33, 69);\n"
                                         "color: rgb(250, 250, 250);\n"
                                         "\n"
                                         "}color: rgb(0, 0, 0);")
        self.PB_right_user.setObjectName("PB_right_user")
        self.HLay_right_button.addWidget(self.PB_right_user)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLay_right_button.addItem(spacerItem1)
        self.PB_right_admin = QtWidgets.QPushButton(self.VLay_contact)
        self.PB_right_admin.setMaximumSize(QtCore.QSize(150, 25))
        self.PB_right_admin.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.PB_right_admin.setFont(font)
        self.PB_right_admin.setStyleSheet("QPushButton{\n"
                                          "background-color: rgb(151, 156, 180);\n"
                                          "    color: rgb(0, 0, 0);\n"
                                          "border-style: solid;\n"
                                          "border-width: 0.5px;\n"
                                          "    border-color: rgb(151, 156, 180);\n"
                                          "border-radius: 5px;\n"
                                          "\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "background-color: rgb(140, 148, 180);\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed {\n"
                                          "border-style: inset;\n"
                                          "\n"
                                          "    \n"
                                          "    background-color: rgb(24, 33, 69);\n"
                                          "color: rgb(250, 250, 250);\n"
                                          "\n"
                                          "}color: rgb(0, 0, 0);")
        self.PB_right_admin.setObjectName("PB_right_admin")
        self.HLay_right_button.addWidget(self.PB_right_admin)
        self.verticalLayout.addLayout(self.HLay_right_button)
        ###################################################################
        self.gridLayout_2.addWidget(self.VLay_contact, 2, 1, 1, 1)
        self.VLay_work_inf_2 = QtWidgets.QFrame(self.frame_loadCard)
        self.VLay_work_inf_2.setObjectName("VLay_work_inf_2")
        self.VLay_work_inf = QtWidgets.QVBoxLayout(self.VLay_work_inf_2)
        self.VLay_work_inf.setObjectName("VLay_work_inf")
        self.label_head_depart = QtWidgets.QLabel(self.VLay_work_inf_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_head_depart.setFont(font)
        self.label_head_depart.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_head_depart.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.label_head_depart.setObjectName("label_head_depart")
        self.VLay_work_inf.addWidget(self.label_head_depart)
        self.line_depart = QtWidgets.QFrame(self.VLay_work_inf_2)
        self.line_depart.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_depart.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_depart.setObjectName("line_depart")
        self.VLay_work_inf.addWidget(self.line_depart)
        self.label_name_depart = QtWidgets.QLabel(self.VLay_work_inf_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_name_depart.setFont(font)
        self.label_name_depart.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name_depart.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_name_depart.setObjectName("label_name_depart")
        self.VLay_work_inf.addWidget(self.label_name_depart)
        self.label_hed_post = QtWidgets.QLabel(self.VLay_work_inf_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_hed_post.setFont(font)
        self.label_hed_post.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_hed_post.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.label_hed_post.setObjectName("label_hed_post")
        self.VLay_work_inf.addWidget(self.label_hed_post)
        self.line_post = QtWidgets.QFrame(self.VLay_work_inf_2)
        self.line_post.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_post.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_post.setObjectName("line_post")
        self.VLay_work_inf.addWidget(self.line_post)
        self.label_name_post = QtWidgets.QLabel(self.VLay_work_inf_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_name_post.setFont(font)
        self.label_name_post.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name_post.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_name_post.setObjectName("label_name_post")
        self.VLay_work_inf.addWidget(self.label_name_post)
        self.label_head_salaryl = QtWidgets.QLabel(self.VLay_work_inf_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_head_salaryl.setFont(font)
        self.label_head_salaryl.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_head_salaryl.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_head_salaryl.setObjectName("label_head_salaryl")
        self.VLay_work_inf.addWidget(self.label_head_salaryl)
        self.line_salaryl = QtWidgets.QFrame(self.VLay_work_inf_2)
        self.line_salaryl.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_salaryl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_salaryl.setObjectName("line_salaryl")
        self.VLay_work_inf.addWidget(self.line_salaryl)
        self.label_salaryl = QtWidgets.QLabel(self.VLay_work_inf_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_salaryl.setFont(font)
        self.label_salaryl.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_salaryl.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTop | QtCore.Qt.AlignTrailing)
        self.label_salaryl.setObjectName("label_salaryl")
        self.VLay_work_inf.addWidget(self.label_salaryl)
        self.gridLayout_2.addWidget(self.VLay_work_inf_2, 3, 0, 1, 1)
        self.frame_loadList = QtWidgets.QFrame(self.frame_person_interaction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_loadList.sizePolicy().hasHeightForWidth())
        self.frame_loadList.setSizePolicy(sizePolicy)
        self.frame_loadList.setMaximumSize(QtCore.QSize(550, 16777215))
        self.frame_loadList.setObjectName("frame_loadList")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_loadList)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.GLay_param_load = QtWidgets.QFrame(self.frame_loadList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLay_param_load.sizePolicy().hasHeightForWidth())
        self.GLay_param_load.setSizePolicy(sizePolicy)
        self.GLay_param_load.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GLay_param_load.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GLay_param_load.setObjectName("GLay_param_load")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GLay_param_load)
        self.gridLayout_3.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        self.ComboBox_Dep_LPers = QtWidgets.QComboBox(self.GLay_param_load)
        self.ComboBox_Dep_LPers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboBox_Dep_LPers.setObjectName("ComboBox_Dep_LPers")
        self.gridLayout_3.addWidget(self.ComboBox_Dep_LPers, 1, 0, 1, 1)
        self.ComboBox_Meanval_LPers = QtWidgets.QComboBox(self.GLay_param_load)
        self.ComboBox_Meanval_LPers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboBox_Meanval_LPers.setObjectName("ComboBox_Meanval_LPers")
        self.ComboBox_Meanval_LPers.addItem("")
        self.ComboBox_Meanval_LPers.addItem("")
        self.ComboBox_Meanval_LPers.addItem("")
        self.gridLayout_3.addWidget(self.ComboBox_Meanval_LPers, 1, 6, 1, 1)
        self.label_Meanval_LPers = QtWidgets.QLabel(self.GLay_param_load)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Meanval_LPers.setFont(font)
        self.label_Meanval_LPers.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Meanval_LPers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Meanval_LPers.setObjectName("label_Meanval_LPers")
        self.gridLayout_3.addWidget(self.label_Meanval_LPers, 0, 6, 1, 1)
        self.ComboBox_Filter_LPers = QtWidgets.QComboBox(self.GLay_param_load)
        self.ComboBox_Filter_LPers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboBox_Filter_LPers.setObjectName("ComboBox_Filer_LPers")
        self.ComboBox_Filter_LPers.addItem("")
        self.ComboBox_Filter_LPers.addItem("")
        self.ComboBox_Filter_LPers.addItem("")
        self.ComboBox_Filter_LPers.addItem("")
        self.gridLayout_3.addWidget(self.ComboBox_Filter_LPers, 1, 4, 1, 1)
        self.label_Filter_LPers = QtWidgets.QLabel(self.GLay_param_load)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Filter_LPers.setFont(font)
        self.label_Filter_LPers.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Filter_LPers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Filter_LPers.setObjectName("label_Filter_LPers")
        self.gridLayout_3.addWidget(self.label_Filter_LPers, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 3, 1, 1)
        self.TB_Date_LPers = QtWidgets.QToolButton(self.GLay_param_load)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TB_Date_LPers.sizePolicy().hasHeightForWidth())
        self.TB_Date_LPers.setSizePolicy(sizePolicy)
        self.TB_Date_LPers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TB_Date_LPers.setStyleSheet("\n"
                                         "border:none\\n")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/calendar.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_Date_LPers.setIcon(icon)
        self.TB_Date_LPers.setIconSize(QtCore.QSize(25, 25))
        self.TB_Date_LPers.setObjectName("TB_Date_LPers")
        self.gridLayout_3.addWidget(self.TB_Date_LPers, 1, 8, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 5, 1, 1)
        self.ComboBox_Crit_LPers = QtWidgets.QComboBox(self.GLay_param_load)
        self.ComboBox_Crit_LPers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboBox_Crit_LPers.setObjectName("ComboBox_Crit_LPers")
        self.gridLayout_3.addWidget(self.ComboBox_Crit_LPers, 1, 2, 1, 1)
        self.label_Date_Lpers = QtWidgets.QLabel(self.GLay_param_load)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Date_Lpers.setFont(font)
        self.label_Date_Lpers.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Date_Lpers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date_Lpers.setObjectName("label_Date_Lpers")
        self.gridLayout_3.addWidget(self.label_Date_Lpers, 0, 8, 1, 1)
        self.Label_Dep_LPers = QtWidgets.QLabel(self.GLay_param_load)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Dep_LPers.setFont(font)
        self.Label_Dep_LPers.setStyleSheet("\n"
                                           "color: rgb(255, 255, 255);")
        self.Label_Dep_LPers.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Dep_LPers.setObjectName("Label_Dep_LPers")
        self.gridLayout_3.addWidget(self.Label_Dep_LPers, 0, 0, 1, 1)
        self.label_Crit_LPers = QtWidgets.QLabel(self.GLay_param_load)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Crit_LPers.setFont(font)
        self.label_Crit_LPers.setStyleSheet("\n"
                                            "color: rgb(255, 255, 255);")
        self.label_Crit_LPers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Crit_LPers.setObjectName("label_Crit_LPers")
        self.gridLayout_3.addWidget(self.label_Crit_LPers, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.GLay_param_load)


        ################Leaf###########################################
        self.VLay_Leaf = QtWidgets.QVBoxLayout()
        self.VLay_Leaf.setObjectName("VLay_Leaf")
        self.HLay_NumPageList = QtWidgets.QHBoxLayout()
        self.HLay_NumPageList.setObjectName("HLay_NumPageList")
        spacerItem9 = QtWidgets.QSpacerItem(210, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.HLay_NumPageList.addItem(spacerItem9)
        self.TB_Left_LPers = QtWidgets.QToolButton(self.frame_loadList)
        self.TB_Left_LPers.setStyleSheet("\n"
                                         "border:none\\n")
        self.TB_Left_LPers.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/arrow_left [#336].png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_Left_LPers.setIcon(icon2)
        self.TB_Left_LPers.setObjectName("TB_Left_LPers")
        self.HLay_NumPageList.addWidget(self.TB_Left_LPers)
        self.Label_NumCurrentList = QtWidgets.QLabel(self.frame_loadList)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Label_NumCurrentList.setFont(font)
        self.Label_NumCurrentList.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_NumCurrentList.setObjectName("Label_NumCurrentList")
        self.HLay_NumPageList.addWidget(self.Label_NumCurrentList)
        self.Label_NumLastList = QtWidgets.QLabel(self.frame_loadList)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Label_NumLastList.setFont(font)
        self.Label_NumLastList.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_NumLastList.setObjectName("Label_NumLastList")
        self.HLay_NumPageList.addWidget(self.Label_NumLastList)
        self.TB_Right_LPers = QtWidgets.QToolButton(self.frame_loadList)
        self.TB_Right_LPers.setStyleSheet("\n"
                                          "border:none\\n")
        self.TB_Right_LPers.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/arrow_right [#336].png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_Right_LPers.setIcon(icon3)
        self.TB_Right_LPers.setObjectName("TB_Right_LPers")
        self.HLay_NumPageList.addWidget(self.TB_Right_LPers)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLay_NumPageList.addItem(spacerItem10)
        self.PB_serch_personalList = QtWidgets.QPushButton(self.frame_loadList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_serch_personalList.sizePolicy().hasHeightForWidth())
        self.PB_serch_personalList.setSizePolicy(sizePolicy)
        self.PB_serch_personalList.setMaximumSize(QtCore.QSize(70, 26))
        self.PB_serch_personalList.setStyleSheet("background-color: rgb(145, 158, 208);")
        self.PB_serch_personalList.setObjectName("PB_serch_personalList")
        self.HLay_NumPageList.addWidget(self.PB_serch_personalList)
        self.VLay_Leaf.addLayout(self.HLay_NumPageList)
        self.label_AllPersonal = QtWidgets.QLabel(self.frame_loadList)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_AllPersonal.setFont(font)
        self.label_AllPersonal.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_AllPersonal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AllPersonal.setObjectName("label_AllPersonal")
        self.VLay_Leaf.addWidget(self.label_AllPersonal)
        self.verticalLayout_5.addLayout(self.VLay_Leaf)
        ###########################################################################
        ###################ADD REMOVE EDIT RULE####################################
        self.VLay_ToolButton = QtWidgets.QFrame(self.frame_loadCard)
        self.VLay_ToolButton.setObjectName("VLay_ToolButton")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.VLay_ToolButton)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TB_AddPersonal = QtWidgets.QToolButton(self.VLay_ToolButton)
        self.TB_AddPersonal.setStyleSheet("\n"
                                          "border:none\\n")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/plus_mini [#1523].png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_AddPersonal.setIcon(icon)
        self.TB_AddPersonal.setIconSize(QtCore.QSize(19, 19))
        self.TB_AddPersonal.setObjectName("TB_AddPersonal")
        self.verticalLayout_2.addWidget(self.TB_AddPersonal)
        self.TB_EditPersonal = QtWidgets.QToolButton(self.VLay_ToolButton)
        self.TB_EditPersonal.setStyleSheet("\n"
                                           "border:none\\n")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/pen [#1320].png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_EditPersonal.setIcon(icon1)
        self.TB_EditPersonal.setIconSize(QtCore.QSize(19, 19))
        self.TB_EditPersonal.setObjectName("TB_EditPersonal")
        self.verticalLayout_2.addWidget(self.TB_EditPersonal)
        self.TB_RemovePersonal = QtWidgets.QToolButton(self.VLay_ToolButton)
        self.TB_RemovePersonal.setStyleSheet("\n"
                                             "border:none\\n")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "C:\\Users\\Yura\\PycharmProjects\\pythonProject\\my_project\\furniture_factory\\GUI_designer\\icon/icons8-удалить-96.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_RemovePersonal.setIcon(icon2)
        self.TB_RemovePersonal.setIconSize(QtCore.QSize(20, 20))
        self.TB_RemovePersonal.setObjectName("TB_RemovePersonal")
        self.verticalLayout_2.addWidget(self.TB_RemovePersonal)
        self.gridLayout_2.addWidget(self.VLay_ToolButton, 2, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_loadCard)
        ########################################################################################
        self.horizontalLayout_3.addWidget(self.frame_loadList)