# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yura\PycharmProjects\pythonProject\furniture_factory\GUI_designer\FF_GUI_soft_mainv1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow ):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 545)
        MainWindow.setStyleSheet("background-color: rgb(74, 80, 106);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 80, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 120, 451, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 290, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 290, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_Creat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Creat.setGeometry(QtCore.QRect(230, 200, 91, 71))
        self.pushButton_Creat.setStyleSheet("QPushButton" "{" "background-color: rgb(52, 154, 159);" "}""QPushButton::hover" "{" "background-color: rgb(48, 129, 159);" "} :disabled { background-color: rgb(128, 128, 128)}")
        self.pushButton_Creat.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./GUI/icon/window_plus [#1463].png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Creat.setIcon(icon)
        self.pushButton_Creat.setIconSize(QtCore.QSize(37, 37))
        self.pushButton_Creat.setObjectName("pushButton")
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Open.setGeometry(QtCore.QRect(460, 200, 91, 71))
        self.pushButton_Open.setStyleSheet("QPushButton" "{" "background-color: rgb(52, 154, 159);" "}""QPushButton::hover" "{" "background-color: rgb(48, 129, 159);" "} :disabled { background-color: rgb(128, 128, 128)}")
        self.pushButton_Open.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./GUI/icon/icon_open_white2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Open.setIcon(icon1)
        self.pushButton_Open.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Open.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.TB_IPEnter = QtWidgets.QToolButton(self.centralwidget)
        self.TB_IPEnter.setGeometry(QtCore.QRect(740, 20, 31, 31))
        self.TB_IPEnter.setStyleSheet(" border-width: 1px;\n"
                                      " border-style: solid;\n"
                                      " border-color:  rgb(158, 158, 158);\n"
                                      "background-color: rgb(96, 105, 138);\n"
                                      "border-radius: 5px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./GUI/icon/arrow_right [#336].png"),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TB_IPEnter.setIcon(icon2)
        self.TB_IPEnter.setShortcut("")
        self.TB_IPEnter.setObjectName("TB_IPEnter")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добро пожаловать в MyFactory"))
        self.label_2.setText(_translate("MainWindow", "Эффективно управляйте предприятем и оценивайте персонал"))
        self.label_3.setText(_translate("MainWindow", "Создать предприятие"))
        self.label_4.setText(_translate("MainWindow", "Открыть мое предприятие"))
        self.TB_IPEnter.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" color:#ffffff;\">Поключиться к серверу</span></p></body></html>"))
        self.TB_IPEnter.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
